### PR TITLE
Radio bugfix & returned value attribute value for checkable inputs.

### PR DESCRIPTION
**Pull request by jackmoore**
`selected` isn't an attribute of radio elements, they use `checked` just like checkboxes. Checkboxes and radios have a value attribute, so that attribute value should be returned instead of the checked state.

See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input

> A radio button. You must use the value attribute to define the value submitted by this item. Use the checked attribute to indicate whether this item is selected by default.

### CODE REVIEW

**Comment by jonathanong** [comment]
oops. added on npm and added as collab.

also, the closest stuff is for `fieldset[disabled]`s

**Comment by jackmoore** [comment]
> also, the closest stuff is for fieldset[disabled]

Good point, thanks.

**Comment by jackmoore** [comment]
Refactored in a different commit.

**Comment by jackmoore** [comment]
Thanks for adding as collaborator, let me know if you have any objections to the change.

**Pull request closed without merging**
